# ArgoCD/Helm merge theo key auth-service (template đọc index .Values "auth-service")
auth-service:
  fullnameOverride: auth-service
  enabled: true
  image:
    repository: registry.gitlab.com/kiettt164/banking-demo-payment/auth-service
    tag: v1
    pullPolicy: Always
  imagePullSecrets: []
  replicas: 2
  service:
    port: 8001
    portName: http
  secretRef:
    name: banking-db-secret
    keys:
      databaseUrl: DATABASE_URL
      redisUrl: REDIS_URL
  corsOrigins: "http://localhost:3000"
  extraEnv: {}
  readinessProbe:
    enabled: true
    path: /health
    port: 8001
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "2000m"
  securityContext:
    pod:
      seccompProfile:
        type: RuntimeDefault
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
