# ArgoCD/Helm merge theo key account-service
account-service:
  fullnameOverride: account-service
  enabled: true
  image:
    repository: registry.gitlab.com/kiettt164/banking-demo-payment/account-service
    tag: v1
    pullPolicy: Always
  imagePullSecrets: []
  replicas: 1
  service:
    port: 8002
    portName: http
  secretRef:
    name: banking-db-secret
    keys:
      databaseUrl: DATABASE_URL
      redisUrl: REDIS_URL
  corsOrigins: "http://localhost:3000"
  extraEnv: {}
  readinessProbe:
    enabled: true
    path: /health
    port: 8002
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "600m"
  securityContext:
    pod:
      seccompProfile:
        type: RuntimeDefault
    container:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
